name = "isol-b2b-web"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[vars]
VITE_WSS_URL = "wss://api.isol.live/audio"

[[kv_namespaces]]
binding = "CF_KV_OTP"
id = "74d6c66c1ef344fdb062c23728927f6a"
preview_id = "74d6c66c1ef344fdb062c23728927f6a"

[[kv_namespaces]]
binding = "CF_KV_RL"
id = "8dfe8a4e78484ff4b99f0ce4d1ff769e"
preview_id = "9ce666e3996f4406b9ee905992b1bf6f"

[[d1_databases]]
binding = "DB"
database_name = "isol-studio"
database_id = "4c445043-15ec-426c-bfaf-26e05f38de2c"
